#!/usr/bin/python3
import random
number = random.randint(-10000, 10000)
r = abs(number) % 10

if number < 0:
    r = -r
print("Last digit of {} is {} ".format(number, r), end="")

if r == 0:
    print("and is 0")
elif r > 5:
    print("and is greater than 5")
else:
    print("and is less than 6 and not 0")
